hw1-fix - Доработки
simonnik/GB_Backend2_GO pull request #3
Opened 2022-06-27 04:57 UTC by simonnik

2022-06-27 18:45 UTC, rumyantseva requested changes
Здорово, что учли замечания и доработали код! 
Это то, что я имела в виду, да!

Добавила ещё несколько идей для доработки ;)

2022-06-27 18:45 UTC, rumyantseva commented on cmd/company/main.go
> +	defer db.Close()
Здесь сигнатура, возможно, тоже предполагает возврат ошибки. Мы уже и так выходим из функции, так что особо ошибку не обработать... Но, тем не менее, можно её залогировать. Если что-то пойдёт не так, такие логи могут пригодиться. Вот что-то примерно такое (но синтаксис лучше проверить еще раз):


```suggestion
	defer func() {
		err := db.Close()
		if err != nil {
			log.Errorf("closing db conn: %w", err)
		}
	  }
	 }()
```

2022-06-27 18:45 UTC, rumyantseva commented on cmd/company/main.go
> +	for {
Кажется, этот `for` лишний :)

Нам тут не нужен бесконечный цикл, если пришла ошибка или сигнал остановки, то просто выходим, на следующую итерацию идти не надо.

2022-06-27 18:45 UTC, rumyantseva commented on cmd/company/main.go
> +		}
1. Поскольку и `err`, и `ctx.Done()` обрабатываются одинаково, можно вынести обработку за `select`.

2. Логировать с уровнем `Fatal` здесь плохо, т.к. `Fatal` приведет к немедленному завершению приложения (и даже `defer`'ы не выполнятся). В этом месте приложения мы уже и так выходим, уровня `Error` достаточно (сами логи важны, чтобы в них потом покопаться, да).

```suggestion
		case err := <-srv.Err:
			log.Errorf("got an error from the server: %w", err)
		case <-ctx.Done():
		}
		
		cancel()
		wg.Wait()
```

2022-06-27 18:45 UTC, rumyantseva commented on internal/repo/memory/memory.go
> +type InMemory struct {
Оставлю общий комментарий на весь пакет - со всеми `InMemory` штуками надо очень аккуратно работать в плане конкурентного доступа к ресурсам. Что будет, если придут несколько запросов одновременно? Как сработают Ваши функции? Похоже, что будет где-то race condition.

2022-06-28 03:03 UTC, simonnik commented on cmd/company/main.go
> +	defer db.Close()
к сожалению, ошибки не возвращает сам пакет, но сам посыл я понял

2022-06-28 03:04 UTC, simonnik commented on cmd/company/main.go
> +	for {
согласен

2022-06-28 03:20 UTC, simonnik commented on internal/repo/memory/memory.go
> +type InMemory struct {
я правильно понимаю, что речь идет про мьютексы?

2022-06-28 21:44 UTC, rumyantseva commented on internal/repo/memory/memory.go
> +type InMemory struct {
Да :)

2022-06-28 21:44 UTC, rumyantseva approved these changes
Предлагаю этот PR вмержить, и мьютексы можно отдельно потом доделать.

2022-06-30 02:32 UTC, merged